### ISSUE TITLE
Permissions for single vs bulk search

### ISSUE THREAD

**Issue by Victordmdb** [stalniy/casl#221] opened 2019-09-02 04:17 UTC
How would one limit the users ability to do bulk search on a collection?

An example use case:

You have user Wish Lists with some items, where the user can share individual items with others. The receiving user should be able to see some basic information about the wish list (_id, name, owner), but access should be limited to the item that was shared.

With CASL i would define 
```
  can("crud", "wishlist", {owner : currentUser});
  can("read", "wishlist",["_id","name","owner"]);

  can("crud", "listitem", {owner : currentUser});
  can("read", "listitem", { sharedWith : currentUser });
```

This has the side-effect that users can bulk search all wishlists and owners, but the intent was only for them to have limited access to the specific wishlist associated with the item that was shared with them.

**Comment by stalniy** [comment] 2019-09-02 05:18
this is due to how you defined abilities. What you need to do is to add condition:

```js
can("read", "wishlist", { sharedWith: currentUser }, ["_id","name","owner"]);

```

**Comment by Victordmdb** [comment] 2019-09-02 05:22
Actually there is no "sharedWith" field on the wishlist, it's only on the list items, since i don't want the user on the receiving end to be able to see all the items of the wishlist. It's a slightly contrived example, but my actual use case is more complex.

**Comment by stalniy** [comment] 2019-09-09 05:14
OK, the provided conditions say this:
* shop owner can CRUD open and closed shops
* others can READ any shop with status open
* shop owner can CRUD available/unavailable products
* others can READ any available products
This is because conditions (regular ones, not invered) for the same subject type are combined by OR logic, so the 1st 2 `can` says: shop can be read if either user is the owner or shop's status is "open"

Based on this:
> Our main concern is that we don't want random users to be able to list shops

I guess you want this:
* shop owner can CRUD own open and closed shops
* others cant READ open shops
* shop owner can CRUD available/unavailable products
* others can READ any available products

If this is correct then:

```js
can("crud", "shop", {owner : currentUser});
can("read", "shop",["_id","name","owner"], { status : "open", owner: currentUser });

can("crud", "product", {owner : currentUser});
can("read", "product", { status: "available"});
```

**P.S.:* frankly speaking it's still hard to understand where the issue :) By the way, where do you check permissionis, on controller/resolver/middleware level or on model level?

**To the 1st version of your comment**: if you don't have required field on your model, then you will need to add one or do permission checks in memory (as far as I remember you use mongodb) on prepopulated model (i.e., it has required field for permission checks)

**Comment by Victordmdb** [comment] 2019-09-10 05:00
No worries, the fact you're taking the time to answer at all is great.

So in the example, you provided seems like the 2nd rule would be redundant no?

I'm currently checking on the model level, using `accessibleBy`.

I think my challenge is due to the fact I'm [modelling a tree structure](https://docs.mongodb.com/manual/applications/data-models-tree-structures/), whereas if I'm querying a child element I want to get the direct ancestors of that child element. 

But currently with CASL, if I give access to those ancestor elements, it means that they can bulk query the entire collection of those parents, while all I wanted was for them to access the hierarchical data.

Its an issue of giving permission to list all from a collection vs querying a single element by id. I guess what I'm asking is, is there a way to implement `readOne` vs `readAll` with CASL?

Does that make more sense?

**Comment by stalniy** [comment] 2019-09-15 05:10
Probably the best way to continue our discussion is to create a small example. So that it's more clear for both of us what the result should be and how to achieve it :)

There are 2 repos which you can fork to quickly setup the example:
* contains simple blog API: https://github.com/stalniy/casl-express-example (I guess you will need to update dependencies)
* mongoose sample with typescript https://github.com/stalniy/casl-mongoose-example (here we can just test in single file and see the result in terminal)

**Comment by stalniy** [comment] 2019-09-28 15:03
@Victordmdb did you have a change to create an example repo or did you find a solution?

**Comment by Victordmdb** [comment] 2019-09-29 10:27
Hi, so sorry it skipped my mind. Heres the code :

`import * as mongoose from 'mongoose'
import { AbilityBuilder } from '@casl/ability'
import { accessibleRecordsPlugin, permittedFieldsPlugin } from '@casl/mongoose'
import { pick } from 'lodash'

import { Types } from "mongoose"

mongoose.plugin(accessibleRecordsPlugin)
mongoose.plugin(permittedFieldsPlugin)

const ability = ( currentUser : string) => AbilityBuilder.define((can : Function) => {
  can("crud", "Category", { owner : currentUser });
  can("read", "Category", ["_id","name","owner"], { public : true });

  can("crud", "Product", { owner : currentUser });
  can("read", "Product", { public : true });
});

const CategorySchema = new mongoose.Schema({
  title       : String,
  owner       : String,
  public      : { type: Boolean, default: false }
});

const ProductSchema = new mongoose.Schema({
  category      : { type : Types.ObjectId, ref : 'Category', required: true },
  name      : String,
  public    : { type: Boolean, default: false }
});

const BobUser = "Bob";
const CharlesUser = "Charles";

const Category = mongoose.model('Category', CategorySchema);
const Product = mongoose.model('Product', ProductSchema);

async function main() {
  await mongoose.connect('mongodb://localhost/casl_test');

  await Promise.all([
    Category.create({
      title: 'Public Category A',
      owner: BobUser,
      public: true
    }),
    Category.create({
      title: 'Hidden Category B',
      owner: BobUser,
      public: false
    }),
    Category.create({
      title: 'Public Category C',
      owner: CharlesUser,
      public: true
    }),
    Category.create({
      title: 'Hidden Category D',
      owner: CharlesUser,
      public: false
    })
  ]);

  const PublicCategoryA = await Category.findOne({name:"Public Category A"});
  const HiddenCategoryB = await Category.findOne({name:"Hidden Category B"});

  const PublicCategoryC = await Category.findOne({name:"Public Category C"});
  const HiddenCategoryD = await Category.findOne({name:"Hidden Category D"});


  await Promise.all([
    Product.create({
      name: 'Product A1',
      category : PublicCategoryA,
      public: true
    }),
    Product.create({
      name: 'Product A2',
      category : PublicCategoryA,
      public: false
    }),
    Product.create({
      name: 'Product B1',
      category : HiddenCategoryB,
      public: true
    }),
    Product.create({
      name: 'Product B2',
      category : HiddenCategoryB,
      public: false
    }),
    Product.create({
      name: 'Product C1',
      category : PublicCategoryC,
      public: true
    }),
    Product.create({
      name: 'Product C2',
      category : PublicCategoryC,
      public: false
    }),
    Product.create({
      name: 'Product D1',
      category : HiddenCategoryD,
      public: true
    }),
    Product.create({
      name: 'Product D2',
      category : HiddenCategoryD,
      public: false
    }),
  ]);

  const currentUser = BobUser;

  // const products = await Product.accessibleBy(ability(currentUser)).find().populate("category");
  //Should contain Products A1, A2, B1, B2, C1 and D1

  const categories = await Category.accessibleBy(ability(currentUser)).find();
  //Should contain only categories A, B

  return categories.every( c => c.owner === currentUser );
}

main()
  .then(console.log)
  .catch(console.error)
  .then(() => mongoose.connection.close())
`

**Comment by stalniy** [comment] 2020-04-22 17:03
Looks like you want to query child model based on parent's one field. CASL currently doesn't support this. It will require to send 2 queries: the first to all ids from `Category` based on their owner and the second to get `Products` based on retrieved ids. 

If you do so, you will be able to get `Products A1, A2, B1, B2, C1 and D1`. 

>  is there a way to implement readOne vs readAll with CASL?

If you want to set permissions separately on one or all records, check #259 it should help.

**Comment by stalniy** [comment] 2020-04-22 17:09
I close this for tidiness. Hopefully you found the right solution in your situation.

**P.S.**: frankly speaking I still don't see where the issue is :) We discussed 3 different domains, despite the fact they are similar it's hard to understand clearly what you have and what you want to achieve.

**Closed by stalniy** 2020-04-22 17:09 UTC
Labels: question
