### ISSUE TITLE
Can't import the  named export 'nin' from non EcmaScript module

### ISSUE THREAD

**Issue by Joeb3219** [stalniy/casl#427] opened 2020-12-31 21:19 UTC
**Describe the bug**
Get the following error:
```
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5035-5036
Can't import the named export '$all' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5076-5077
Can't import the named export '$elemMatch' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:4983-4984
Can't import the named export '$eq' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5086-5087
Can't import the named export '$exists' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5008-5009
Can't import the named export '$gt' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5015-5016
Can't import the named export '$gte' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5021-5022
Can't import the named export '$in' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:4995-4996
Can't import the named export '$lt' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5002-5003
Can't import the named export '$lte' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:4989-4990
Can't import the named export '$ne' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5028-5029
Can't import the named export '$nin' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5063-5064
Can't import the named export '$options' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5052-5053
Can't import the named export '$regex' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5043-5044
Can't import the named export '$size' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/mongo/dist/es6m/index.mjs 1:955-956
Can't import the named export 'CompoundCondition' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/mongo/dist/es6m/index.mjs 1:910-911
Can't import the named export 'FieldCondition' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/mongo/dist/es6m/index.mjs 1:1223-1224
Can't import the named export 'FieldCondition' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/mongo/dist/es6m/index.mjs 1:2006-2007
Can't import the named export 'FieldCondition' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/mongo/dist/es6m/index.mjs 1:1203-1204
Can't import the named export 'ITSELF' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/js/dist/es6m/index.mjs 1:597-598
Can't import the named export 'ITSELF' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/js/dist/es6m/index.mjs 1:1566-1567
Can't import the named export 'ITSELF' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/js/dist/es6m/index.mjs 1:1867-1868
Can't import the named export 'ITSELF' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/mongo/dist/es6m/index.mjs 1:2054-2055
Can't import the named export 'NULL_CONDITION' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/mongo/dist/es6m/index.mjs 1:2306-2307
Can't import the named export 'ObjectQueryParser' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5145-5146
Can't import the named export 'all' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5187-5188
Can't import the named export 'and' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/mongo/dist/es6m/index.mjs 1:2427-2428
Can't import the named export 'buildAnd' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5207-5208
Can't import the named export 'createFactory' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5265-5266
Can't import the named export 'createFactory' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/js/dist/es6m/index.mjs 1:971-972
Can't import the named export 'createInterpreter' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5172-5173
Can't import the named export 'elemMatch' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5101-5102
Can't import the named export 'eq' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5181-5182
Can't import the named export 'exists' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5122-5123
Can't import the named export 'gt' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5128-5129
Can't import the named export 'gte' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5111-5112
Can't import the named export 'lt' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5117-5118
Can't import the named export 'lte' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5106-5107
Can't import the named export 'ne' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5139-5140
Can't import the named export 'nin' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/mongo/dist/es6m/index.mjs 1:625-626
Can't import the named export 'optimizedCompoundCondition' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5160-5161
Can't import the named export 'regex' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5152-5153
Can't import the named export 'size' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@casl/ability/dist/es6m/index.mjs 1:5133-5134
Can't import the named export 'within' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/@ucast/mongo/dist/es6m/index.mjs 1:169-238
Can't reexport the named export 'defaultInstructionParsers' from non EcmaScript module (only default export is available)
```

**To Reproduce**
1. Created a yarn monorepo w/ an angular project. 
2. Using `commonjs` as my tsconfig module, `es2015`, `dom`, and `es6` as my libs, `es2015` as my target.
3. Compile app

I am not even trying to use the angular bindings -- when I do drop it into my module's imports, I get errors about Ivy compatibility/ngcc, even though I've run ngcc.

**CASL Version**
`@casl/ability` - 5.1.1

**Environment**:
TS 4.0.3, Node 12.13.0, Angular 11.0.2

**Comment by stalniy** [comment] 2020-12-31 22:49
I’ve not tested casl with angular v11 but it seems to be a webpack related issue. Please read explanation in the docs - https://casl.js.org/v5/en/guide/install#webpack

**Comment by stalniy** [comment] 2021-01-01 07:47
Related https://lifesaver.codes/answer/webpack-4-compatibility-issue

I’ll check why webpack picks wrong bundle for ucast module. Ucast actually have ES6.mjs file as well

**Comment by miltonhowe** [comment] 2021-01-02 02:31
FWIW I am having the same issue with a fresh install of @casl/angular.
TS 4.0.5 Node v14.1.0 Angular 11.0.4
The error messages are followed by this (helpful^) suggestion:
```
 Error: node_modules/@casl/angular/dist/types/AbilityModule.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (@casl/angular) which declares AbilityModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

**Comment by DerekJDev** [comment] 2021-01-07 18:32
Any update on this?

**Comment by stalniy** [comment] 2021-01-07 19:50
Sorry, nothing new guys. We are celebrating Orthodox Christmas. So, there won’t be any updates for the next 2-3 days for sure. 

Meanwhile, you can check [casl v5 + angular v10](https://github.com/stalniy/casl-examples/tree/master/packages/angular-todo). It works for sure. Maybe it will help you to make it work for angular v11 as well. 

Please pay attention at https://github.com/stalniy/casl-examples/blob/master/packages/angular-todo/webpack.extend.js#L6

**Comment by stalniy** [comment] 2021-01-10 18:06
The only fix I was able to find for `Can't import the named export '$all' from non EcmaScript module` issue is to mark `mjs` files as `javascript/auto` via [webpack.extend.js](https://github.com/stalniy/casl-examples/blob/master/packages/angular-todo/webpack.extend.js#L6). 

Pure webpack5 and webpack4 correctly handles `mjs` without additional configuration, so I guess there is some angular cli specific magic going on.

Regarding `ngcc` error, it looks like it doesn't work with `.mjs` files... It properly compiles umd and es5m targets but skips es6m for some reason. Will try to find a workaround for this, I guess the easiest option may be just to ship .js file instead of `.mjs` for casl/angular

**Comment by stalniy** [comment] 2021-01-10 20:33
The latest release of @casl/angular fixes ngcc related issue. 

Regarding ESM modules: found [this issue](https://github.com/angular/angular-cli/issues/11527) regarding angular cli and some additional context. The issue is that when webpack imports dependencies inside `.mjs` files, webpack checks only `main` and `browser` fields in package.json. `main` is usually points to `commonjs` and `browser` I think usually points to some global vars. So, there is no reliable way to fix this for webpack4.

So, I suggest to use one of this ways:
1. customize angular webpack file and make `.mjs` files to be of type `javascript/auto` as in example repo. As a downside, your bundle size will be a bit bigger
2. customize `resolve.mainFields` and exclude `es2015` out of it, so webpack won't bundle `.mjs` file at all (use `module` property which is a ES5 +ESM). As a downside, you can deliver a modern build for users
3. use the previous version of casl and wait for angular cli to support webpack 5 which supports `exports` field in `package.json` and properly handles chains of ESM imports

**Comment by stalniy** [comment] 2021-01-11 12:09
There is nothing else I plan to do with this, so close it. But feel free to comment and suggest alternative solutions.

**Closed by stalniy** 2021-01-11 12:09 UTC
Labels: bug

**Comment by stalniy** [comment] 2021-01-11 15:32
One more solution is to use `postinstall` hook and [shx](https://github.com/shelljs/shx) to rename `.mjs` to `.js` while angular cli uses webpack 4. In your app package.json:

```json
{
  "scripts": {
    "postinstall": "npm run fix.casl.esm",
    "prefix.casl.esm": "npx shx cp ./node_modules/@casl/ability/dist/es6m/index.mjs ./node_modules/@casl/ability/dist/es6m/index.js",
    "fix.casl.esm": "npx shx sed -i 's/index.mjs/index.js/g' ./node_modules/@casl/ability/package.json"
  }
}
```

**Comment by d3473r** [comment] 2021-02-18 10:36
> One more solution is to use `postinstall` hook and [shx](https://github.com/shelljs/shx) to rename `.mjs` to `.js` while angular cli uses webpack 4. In your app package.json:
> 
> ```json
> {
>   "scripts": {
>     "postinstall": "npm run fix.casl.esm",
>     "prefix.casl.esm": "npx shx cp ./node_modules/@casl/ability/dist/es6m/index.mjs ./node_modules/@casl/ability/dist/es6m/index.js",
>     "fix.casl.esm": "npx shx sed -i 's/index.mjs/index.js/g' ./node_modules/@casl/ability/package.json"
>   }
> }
> ```

This worked for `@casl/ability`, but i am having the same problem with `@ucast/mongo2js`:
```
Error: ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs 24:13-14
Can't import the named export 'ITSELF' from non EcmaScript module (only default export is available)

Error: ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs 17:14-15
Can't import the named export 'MongoQueryParser' from non EcmaScript module (only default export is available)

Error: ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs 35:13-14
Can't import the named export 'allInterpreters' from non EcmaScript module (only default export is available)

Error: ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs 45:5-6
Can't import the named export 'allInterpreters' from non EcmaScript module (only default export is available)

Error: ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs 35:10-11
Can't import the named export 'allParsingInstructions' from non EcmaScript module (only default export is available)

Error: ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs 40:21-22
Can't import the named export 'allParsingInstructions' from non EcmaScript module (only default export is available)

Error: ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs 41:26-27
Can't import the named export 'allParsingInstructions' from non EcmaScript module (only default export is available)

Error: ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs 13:9-10
Can't import the named export 'compare' from non EcmaScript module (only default export is available)

[39m[0mError: ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs 18:10-11
Can't import the named export 'createJsInterpreter' from non EcmaScript module (only default export is available)

Error: ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs 32:9-10
Can't import the named export 'createTranslatorFactory' from non EcmaScript module (only default export is available)

Error: ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs 43:11-12
Can't import the named export 'defaultParsers' from non EcmaScript module (only default export is available)
```

This is a dependency of `@casl/ability`
```
λ npm list @ucast/mongo2js 
└─┬ @casl/ability@5.2.2
  └── @ucast/mongo2js@1.3.2
```

Do you have a solution for this dependency?

**Comment by stalniy** [comment] 2021-02-18 19:09
Follow https://github.com/stalniy/casl/issues/427#issuecomment-757518098

or use webpack5

**Comment by paolosanchi** [comment] 2021-03-23 17:20
> ```json
>  "fix.casl.esm": "npx shx sed -i 's/index.mjs/index.js/g' ./node_modules/@casl/ability/package.json"
> ```

This worked for me:

{
  "scripts": {
	"postinstall": "npm run fix.casl.esm && npm run fix.ucast.mongo2js.esm && npm run fix.ucast.mongo.esm && npm run fix.ucast.js.esm",
    "prefix.casl.esm": "npx shx cp ./node_modules/@casl/ability/dist/es6m/index.mjs ./node_modules/@casl/ability/dist/es6m/index.js",
    "fix.casl.esm": "npx shx sed -i 's/index.mjs/index.js/g' ./node_modules/@casl/ability/package.json",
    "prefix.ucast.mongo2js.esm": "npx shx cp ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs ./node_modules/@ucast/mongo2js/dist/es6m/index.js",
    "fix.ucast.mongo2js.esm": "npx shx sed -i 's/index.mjs/index.js/g' ./node_modules/@ucast/mongo2js/package.json",
    "prefix.ucast.mongo.esm": "npx shx cp ./node_modules/@ucast/mongo/dist/es6m/index.mjs ./node_modules/@ucast/mongo/dist/es6m/index.js",
    "fix.ucast.mongo.esm": "npx shx sed -i 's/index.mjs/index.js/g' ./node_modules/@ucast/mongo/package.json",
    "prefix.ucast.js.esm": "npx shx cp ./node_modules/@ucast/js/dist/es6m/index.mjs ./node_modules/@ucast/js/dist/es6m/index.js",
    "fix.ucast.js.esm": "npx shx sed -i 's/index.mjs/index.js/g' ./node_modules/@ucast/js/package.json"
  }
}

**Comment by danmana** [comment] 2021-05-20 09:25
> This worked for me:
> 
> ```
> {
>   "scripts": {
>     "postinstall": "npm run fix.casl.esm && npm run fix.ucast.mongo2js.esm && npm run fix.ucast.mongo.esm && npm run fix.ucast.js.esm",
>     "prefix.casl.esm": "npx shx cp ./node_modules/@casl/ability/dist/es6m/index.mjs ./node_modules/@casl/ability/dist/es6m/index.js",
>     "fix.casl.esm": "npx shx sed -i 's/index.mjs/index.js/g' ./node_modules/@casl/ability/package.json",
>     "prefix.ucast.mongo2js.esm": "npx shx cp ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs ./node_modules/@ucast/mongo2js/dist/es6m/index.js",
>     "fix.ucast.mongo2js.esm": "npx shx sed -i 's/index.mjs/index.js/g' ./node_modules/@ucast/mongo2js/package.json",
>     "prefix.ucast.mongo.esm": "npx shx cp ./node_modules/@ucast/mongo/dist/es6m/index.mjs ./node_modules/@ucast/mongo/dist/es6m/index.js",
>     "fix.ucast.mongo.esm": "npx shx sed -i 's/index.mjs/index.js/g' ./node_modules/@ucast/mongo/package.json",
>     "prefix.ucast.js.esm": "npx shx cp ./node_modules/@ucast/js/dist/es6m/index.mjs ./node_modules/@ucast/js/dist/es6m/index.js",
>     "fix.ucast.js.esm": "npx shx sed -i 's/index.mjs/index.js/g' ./node_modules/@ucast/js/package.json"
>   }
> }
> ```

This worked for me too, but I had to replace the single quotes with *escaped double quotes* (on windows).

```json
{
  "scripts": {
    "postinstall": "npm run fix.casl.esm && npm run fix.ucast.mongo2js.esm && npm run fix.ucast.mongo.esm && npm run fix.ucast.js.esm",
    "prefix.casl.esm": "npx shx cp ./node_modules/@casl/ability/dist/es6m/index.mjs ./node_modules/@casl/ability/dist/es6m/index.js",
    "fix.casl.esm": "npx shx sed -i \"s/index.mjs/index.js/g\" ./node_modules/@casl/ability/package.json",
    "prefix.ucast.mongo2js.esm": "npx shx cp ./node_modules/@ucast/mongo2js/dist/es6m/index.mjs ./node_modules/@ucast/mongo2js/dist/es6m/index.js",
    "fix.ucast.mongo2js.esm": "npx shx sed -i \"s/index.mjs/index.js/g\" ./node_modules/@ucast/mongo2js/package.json",
    "prefix.ucast.mongo.esm": "npx shx cp ./node_modules/@ucast/mongo/dist/es6m/index.mjs ./node_modules/@ucast/mongo/dist/es6m/index.js",
    "fix.ucast.mongo.esm": "npx shx sed -i \"s/index.mjs/index.js/g\" ./node_modules/@ucast/mongo/package.json",
    "prefix.ucast.js.esm": "npx shx cp ./node_modules/@ucast/js/dist/es6m/index.mjs ./node_modules/@ucast/js/dist/es6m/index.js",
    "fix.ucast.js.esm": "npx shx sed -i \"s/index.mjs/index.js/g\" ./node_modules/@ucast/js/package.json"
  }
}
```


@paolosanchi 
Thanks a lot!
This solution works both in dev mode and prod mode.
The `webpack-config` trick with `javascript/auto` did not work when running `--prod`.
