### ISSUE TITLE
Rule condition without instance (user based)

### ISSUE THREAD

**Issue by sarates** [stalniy/casl#230] opened 2019-10-30 08:58 UTC
I can't find a way to implement a rule without class instance. 
For example, I wanna give the possibility to delete a post if in user permissions array (returned via API) presents such string 'post.can_delete'. 
Thanks for the help.

**Comment by stalniy** [comment] 2019-10-30 09:18
Please take a look at https://github.com/stalniy/casl/issues/107#issuecomment-508181122

**Comment by stalniy** [comment] 2019-10-30 09:19
Close as a duplicate of #107

**Closed by stalniy** 2019-10-30 09:19 UTC

**Comment by sarates** [comment] 2019-10-30 09:42
@stalniy Thanks for the quick response.

But I still have a few questions.

1. Can I check user permissions somehow at rule condition?
2. `can` from AbilityBuilder.extract(); expected 2-4 parameters, not only one..

`import { AbilityBuilder, Ability } from '@casl/ability';
import {store} from './store';

let state = null;
store.subscribe(() => {
  state = store.getState();
});

class User {
  constructor(user: any) {
    Object.assign(this, user);
  }
}

const subjectName = () => 'all';

const ability = new Ability([], { subjectName });

const defineRulesFor = (currentLoggedUser: any) => {
  const { can, rules } = AbilityBuilder.extract();

  can('view');

  return rules;
};

let currentLoggedUser: any;

store.subscribe(() => {
  const prevLoggedUser = currentLoggedUser;
  currentLoggedUser = store.getState().app.loggedUserInfo;

  if (prevLoggedUser !== currentLoggedUser) {
    ability.update(defineRulesFor(new User(currentLoggedUser)));
  }
});

export default ability;
`

**Comment by stalniy** [comment] 2019-10-30 10:23
1. Don’t understand what you mean. Could you please show an example
2. Yes it expects more arguments but you can pass only one if you use JavaScript, not typescript. Also complementary libraries doesn’t allow to pass one argument (at least react). So, this feature is not finalized, that’s why there is an open issue :)
