### ISSUE TITLE
@casl/mongoose Accessible Records plugin's doesn't work with classes as subject type

### ISSUE THREAD

**Issue by lavrentious** [stalniy/casl#656] opened 2022-08-05 09:56 UTC
**Describe the bug**
I'm using NestJS+CASL+mongoose (+ casl/mongoose). I have Record and User modules. In `ability/ability.factory.ts` I define ability for mongoose's models and all the checks work correctly both for the RecordModel and its instances from DB. I also have a simple endpoint in `records/records.controller.ts` that retrieves all the Records from the DB that the logged user can access (In the actual project I get the logged user through JWT, but in this example I mock it). I get the logged user's ability using AbilityFactory and pass it to `records/records.service.ts`'s method `find`. However, using `.accessibleBy(ability)` method on the RecordModel throws ForbiddenError saying `Cannot execute "read" on "Record"` despite ability's permissions being sufficient (see **"To reproduce"** section). I have also included some console.logs and comments in `records.controller` and `records.service`.

**To Reproduce**
I've created a [repository](https://github.com/lavrentious/nest-casl-mongoose) with a simple NestJS project with an example of the issue (I couldn't, however, supply it with proper tests).
Clone it, install with `npm ci` and start with `npm run start:dev`.
A GET request to `http://localhost:3000/records/` results in a 403 Forbidden, but is supposed to be a 200 with array of Records.
I've also created a test Mongo cluster with mock data and included the connection URL in the code.

**Expected behavior**
Since ability is able to Read Records, `.accessibleBy()` must not throw ForbiddenError and return proper Query object.

**CASL Version**
`@casl/ability` - v6.0.0
`@casl/mongoose` - v7.0.0

**Environment**:
`nodejs`: v16.16.0
`typescript`: v4.7.4

**Comment by stalniy** [comment] 2022-08-06 05:16
CASL doesn't care what you use nestjs or expressjs. Ideally, I just need 2 things:
1. ability definition example 
2. ability check example

This speeds up testing and feedback. 

Have you tried to do the same without all the heavyweight-ness of nestjs?

**Comment by stalniy** [comment] 2022-08-06 06:12
OK, found the cause. It appears that casl/mongoose doesnt work in case you use classes as subject types. It expects to work with strings only

**Comment by stalniy** [comment] 2022-08-28 13:01
fixed in `@casl/mongoose@7.1.0`

**Closed** 2022-08-28 13:01 UTC
Labels: bug

**Comment by Alex0007** [comment] 2022-10-08 02:42
@stalniy i guess it's not fixed


```typescript
const classrooms = new ClassroomModel(); // Mongoose model instance

// Not working: Cannot execute \"read\" on \"Classroom\"
can('read', classrooms)
console.log(classrooms.constructor.modelName) // "Classroom"

// Working:
can('read', "Classroom")


```

**Comment by Alex0007** [comment] 2022-10-08 03:23
@stalniy I guess it's not fixed

```typescript
const classrooms = new ClassroomModel();
console.log(classrooms.constructor.modelName); // "Classroom"

return defineAbility((can, cannot) => {
  can('read', classrooms)
}
// Error: Cannot execute \"read\" on \"Classroom\"

return defineAbility((can, cannot) => {
  can('read', classrooms.constructor.modelName)
}
// Works, but no typescript support for condition
```

**Comment by stalniy** [comment] 2022-10-08 03:44
Just use ClassroomModel instead of classrooms object in conditions

**Comment by Alex0007** [comment] 2022-10-08 03:53
@stalniy 
it's not working
```typescript
    can('read', ClassroomModel)
    // Cannot execute \"read\" on \"Classroom\"
```

When adding `detectSubjectType: o => o.constructor as SubjectType` – it works. 

But there is another problem with `cannot` rules error message:
<img width="338" alt="Screenshot 2022-10-08 at 07 52 04" src="https://user-images.githubusercontent.com/1143226/194686924-9736c5f6-69f9-4a1d-8451-03dbeaafc242.png">

**Comment by stalniy** [comment] 2022-10-08 04:02
this is how it should work. regarding error message, I will double check

**Comment by Alex0007** [comment] 2022-10-09 00:40
@stalniy 
Here is repro for this incorrect subject name problem

```typescript
import { AbilityBuilder, Ability, defineAbility } from '@casl/ability';
import mongoose from 'mongoose';

const { accessibleRecordsPlugin } = require('@casl/mongoose')

const Article = new mongoose.Schema({
  title: String,
  author: String
})

Article.plugin(accessibleRecordsPlugin)

const ArticleModel = mongoose.model('Article', Article)

const ability = defineAbility((can, cannot) => {
  cannot('read', ArticleModel)
}, {
  detectSubjectType: object => object.constructor as any
})

ArticleModel.accessibleBy(ability).findOne().then(console.log).catch(console.error)
```

Also i noticed another potential problem. When access error is thrown, data is actually exposed in error stack

**Comment by rajkanase** [comment] 2023-02-02 14:05
@stalniy 
For me,
Everything works perfect till @casl/mongoose@7.0.0 but when I upgrade to 7.1.0 and above, it doesn't throw any error but the abilities doesn't work it seems. For USER role also it returns all the records. 
```

    if (user.roles.includes('NASP_ADMIN')) {
      can(Action.Read, 'all');
      can(Action.Update, 'Project', ['isReviewed']);
      can(Action.Delete, 'all');
    } else {
      can(Action.Read, 'Project', { createdBy: user.sub }); // read-only access to own projects
      can(Action.Update, 'Project', ['name', 'projectDescription'], {
        createdBy: user.sub,
      });
    }
```

Expected Behavior - 
For USER role - it should show only the records created by himself.
For ADMIN role - it should show all the records.

**Comment by stalniy** [comment] 2023-02-03 06:02
@rajkanase i don’t see the full picture of your case

but from what I see I can tell that you use strings as subject types not classes. So at least it seems unrelated to this issue.
