### ISSUE TITLE
Doesn't Support es5 Compiler Options - Column must be greater than or equal to 0, got -21

### ISSUE THREAD

**Issue by johnvinosh** [stalniy/casl#387] opened 2020-09-03 08:50 UTC
**Describe the bug**
I changed my compilerOptions to es5 to support IE11 browser and when I run ng serve following error occurs
TypeError: node_modules\@casl\angular\__ivy_ngcc__\dist\es6\index.js: Column must be greater than or equal to 0, got -21

![image](https://user-images.githubusercontent.com/26540475/92091976-1bf18080-edef-11ea-964f-df23618e59cf.png)

![image](https://user-images.githubusercontent.com/26540475/92092071-388db880-edef-11ea-8512-ed7b68d8a1ae.png)

**To Reproduce**
Angular Version: 9.1.2
"@angular/animations": "~9.1.2",
"@angular/cdk": "^9.2.1",
"@angular/common": "~9.1.2",
"@angular/compiler": "~9.1.2",
"@angular/core": "~9.1.2",

**Expected behavior**
Build without error and also should support IE11 browser.

**CASL Version**

`@casl/ability` - 4.1.5
`@casl/angular` - 4.1.4

**Environment**:

Node Version: 12.16.1

**Comment by stalniy** [comment] 2020-09-03 10:18
Looks like a duplicate of #382

**Comment by stalniy** [comment] 2020-09-03 12:40
Unfortunately, I can't reproduce this issue by fixed sourcemaps to point to TypeScript sources instead of intermediate transformation. hopefully this fixes the issue.

Let me know if not and I'll reopen the issue.

**Closed** 2020-09-03 12:48 UTC
Labels: bug, casl/angular

**Comment by stalniy** [comment] 2020-09-03 12:57
I used [this app](https://github.com/stalniy/casl-examples/tree/master/packages/angular-todo) to reproduce the issue.

**Comment by johnvinosh** [comment] 2020-09-03 16:43
Thanks for the quick fix. Working good now.
