### ISSUE TITLE
Inference of subjects in documentation not working?

### ISSUE THREAD

**Issue by anlauren** [stalniy/casl#473] opened 2021-03-04 19:11 UTC
**Describe the bug**
When i try to run the following example in the docs:
```typescript
import { Ability } from '@casl/ability';

interface Article {
  id: number;
  title: string;
  content: string;
  authorId: number;
}

interface User {
  id: number;
  name: string;
}

interface Comment {
  id: number;
  content: string;
  authorId: number;
}

type Action = 'create' | 'read' | 'update' | 'delete';
type Subject = Article | Comment | User | 'Article' | 'User' | 'Comment';

const ability = new Ability<[Action, Subject]>();
```

It is raising a typescript error explaining that Type 'Article' is not assignable to type 'Subject' or Type 'Article' is not assignable to type 'AnyRecord' or Index signature is missing in type 'Article'.

I've tried to google around without luck 🤔 I'm guessing it has something to deal with how strict are the class rules but i'm using a fairly basic ts config

**To Reproduce**
1. just copy paste the above and try to build it

**Expected behavior**
It should build

**CASL Version**

"@casl/ability@^5.2.2"

**Environment**:
node: v10.22.0
"typescript": "^4.0.5"

tsconfig:

```json
{
  "compilerOptions": {
    /* Basic Options */
    "target": "es2018",
    "module": "commonjs",
    "lib": [
      "esnext.asynciterable"
    ],
    "declaration": true /* Generates corresponding '.d.ts' file. */,
    "sourceMap": true /* Generates corresponding '.map' file. */,
    "outDir": "./build" /* Redirect output structure to the directory. */,
<img width="1031" alt="Screenshot 2021-03-04 at 18 37 04" src="https://user-images.githubusercontent.com/7627816/110016701-403a0580-7d1d-11eb-95c3-c64bfbcf1be3.png">

    "removeComments": false /* Do not emit comments to output. */,

    "importHelpers": true /* Import emit helpers from 'tslib'. */,
    "strict": false /* Enable all strict type-checking options. */,
    "noImplicitAny": true /* Raise error on expressions and declarations with an implied 'any' type. */,
    "strictNullChecks": true /* Enable strict null checks. */,
    "strictFunctionTypes": true /* Enable strict checking of function types. */,
    "strictPropertyInitialization": false /* Enable strict checking of property initialization in classes. */,
    "noImplicitThis": true /* Raise error on 'this' expressions with an implied 'any' type. */,
    "alwaysStrict": true /* Parse in strict mode and emit "use strict" for each source file. */,

    /* Additional Checks */
    "noUnusedLocals": false /* Report errors on unused locals. */,
    "noUnusedParameters": false /* Report errors on unused parameters. */,
    "noImplicitReturns": true /* Report error when not all code paths in function return a value. */,
    "noFallthroughCasesInSwitch": true /* Report errors for fallthrough cases in switch statement. */,

    /* Module Resolution Options */
    "moduleResolution": "node" /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */,
   

    "allowSyntheticDefaultImports": true /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */,
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,

    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true /* Don't check libs typings - due to https://github.com/prisma/graphql-request/issues/26 */,


    /* Experimental Options */
    "experimentalDecorators": true /* Enables experimental support for ES7 decorators. */,
    "emitDecoratorMetadata": true /* Enab*/
  }
}
```

<img width="1031" alt="Screenshot 2021-03-04 at 18 37 04" src="https://user-images.githubusercontent.com/7627816/110016742-4cbe5e00-7d1d-11eb-8b7f-c3385a00e2fb.png">

**Comment by stalniy** [comment] 2021-03-04 20:34
Hey, very strange. I’ve noticed there is no kind property on your interfaces. 

Except of that the rest should be fine. Please specify ts version

**Comment by anlauren** [comment] 2021-03-04 20:50
these are my different packages installed:
```
    "ts-jest": "^26.4.3",
    "ts-loader": "^8.0.8",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.0.5"
```
Adding the "kind" doesn't change anything, i've tried with every combination i could but i went back to the example in the docs to report the issue and be sure i was not doing something stupid

<img width="971" alt="Screenshot 2021-03-04 at 20 49 13" src="https://user-images.githubusercontent.com/7627816/110028409-18ea3500-7d2b-11eb-9865-bfa56c2b048f.png">

**Comment by anlauren** [comment] 2021-03-04 21:11
Okay i'm reading the implementation and I don't understand how it's supposed to work 🤔 
```typescript
export declare type Subject = AnyRecord | SubjectType;
```
 -> Either it's a record or a SubjectType. A record can accept any key as value accessor, so something of type `Article` cannot be of type `AnyRecord`

So it has to be of type `SubjectType`.

```typescript
export declare type SubjectType = string | SubjectClass;
```
-> well it's not a string so let's move on

```typescript
export declare type SubjectClass<N extends string = string> = AnyClass & {
    modelName?: N;
};
```
-> so first it has to be AnyClass

```typescript
export declare type AnyClass<ReturnType = any> = new (...args: any[]) => ReturnType;
```
That is a classic definition of class typechecking, which would work for `typeof Article`, but is not true for `Article` since it's an instance.

Hence, i have no idea how it's supposed to work 🤔 I don't know the library enough to understand it all though.
I don't see the point of `& {modelName?: N;}` we're adding an optional constraint?

**Comment by anlauren** [comment] 2021-03-04 21:22
the only way i found to make that work is quite hacky, it's to turn either the class or the interface into a record.
But that allows for unsafe practices (adding random things to the class/object is permitted and reading them as well)

```typescript
import { Ability } from '@casl/ability';

interface IArticle {
  [k: string]: any;
  id: string;
}
class Article implements IArticle {
  [k: string]: any;
  constructor(public id: string) {}
}

type Action = 'create' | 'read' | 'update' | 'delete';
type Subject = Article;

const ability = new Ability<[Action, Subject]>();

const a: IArticle = {
  hello: 'nope',
  id: 'fd',
};

const article = new Article('test');
article.nope = 'works i know';
console.log('That is really unsafe', article.something.else);
ability.can('create', article);

```

**Comment by stalniy** [comment] 2021-03-05 07:36
There are several examples in casl-examples repo that do the same or similar. For example for react: https://github.com/stalniy/casl-examples/blob/master/packages/react-todo/src/config/ability.ts#L8

**Comment by stalniy** [comment] 2021-03-05 07:36
Please check them until I have time to test it by myself

**Comment by stalniy** [comment] 2021-03-05 10:37
I've just create a sample repo: https://github.com/stalniy/casl-ts-inference

And cannot reproduce your issue

**Comment by anlauren** [comment] 2021-03-05 11:46
I am baffled. I cloned the repo and it does work when I run but my VSCode keeps complaining about it so i guess it's on my VS code config somewhere somehow, never seen that happening before. 

There was build errors as well in my project but it might have come from my experiments to try to make it work.

I'm still a bit confused about _why_ it works and build, reading the code i mentioned above, but I guess it's on me to get better at typescript ;p

(My Vscode error in that repo if somebody sees that in the future:)
<img width="802" alt="Screenshot 2021-03-05 at 11 42 35" src="https://user-images.githubusercontent.com/7627816/110111324-0cf08880-7da8-11eb-8181-2de3ca99960e.png">

**Comment by stalniy** [comment] 2021-03-05 12:35
I also use vscode. Check which ts version vscode uses

**Comment by stalniy** [comment] 2021-03-05 12:36
There are some exceptions when interface is assignable to record. I don’t know all of them as well but looks like ts uses one of such exceptions in case of casl

**Comment by stalniy** [comment] 2021-03-05 14:51
OK. I close this. Feel free to comment if you find more information about this.

**Closed by stalniy** 2021-03-05 14:51 UTC
Labels: bug, unconfirmed

**Comment by jamesmeneghello** [comment] 2021-03-09 14:57
This happened to me also, with the root cause being that VS Code was opening using node v12 and my CLI was using node v15.

**Comment by stalniy** [comment] 2021-03-09 15:36
yes, node version cannot affect this only ts version. You need TS ^3.8.3 as far as I remember
