### ISSUE TITLE
@casl/prisma - .mjs file is imported without extension, resulting in ERR_MODULE_NOT_FOUND error

### ISSUE THREAD

**Issue by TissuePowder** [stalniy/casl#701] opened 2022-11-13 18:48 UTC
**Describe the bug**
`index.mjs` file located at `node_modules/@casl/prisma/dist/es6m/` directory has an import statement that goes:
`import {.....} from "./runtime"`. 
Since no file extension is specified, this results in `ERR_MODULE_NOT_FOUND` error.

**To Reproduce**
1. Just import any functionality from `@casl/prisma` and try to use it in your program.

**Expected behavior**
For clarification, manually editing the statement to be `import {.....} from "./runtime.mjs"` solves the problem and everything runs fine. 

**CASL Version**

`@casl/ability` - 6.3.2
`@casl/prisma` - 1.3.1

**Environment**:
Using typescript version 4.8.4, tsconfig file uses following settings:
```
"target": "ES2017",
"module": "ES2022",
"moduleResolution": "node",           
```

**Comment by soulchild** [comment] 2022-11-18 09:53
Probably duplicate of #698

**Comment by stalniy** [comment] 2022-11-18 14:34
close as duplicate of #698

**Closed by stalniy** 2022-11-18 14:34 UTC
Labels: bug
