### ISSUE TITLE
can is not a function in React Native app on Release mode

### ISSUE THREAD

**Issue by GrowingCompany** [stalniy/casl#467] opened 2021-02-24 03:02 UTC
**Describe the bug**
Hello,
I'm using CASL in React-Native App
CASL is working perfectly on Debug Mode.
But when I change from Debug to Release on XCode
occurred error like below.

[TypeError: f is not a function. (In 'f(u.action)', 'f' is undefined)]

It's occurred when call 'can' function.
I don't know what i miss. please help me how to fix this error. 
Thank you!

**To Reproduce**
ReactNative version: 0.60.5
In XCode change build configuration on scheme from Debug to Release

Code:
  defineRulesFor = organization => {
    try {
      const {can, rules} = new AbilityBuilder(Ability);
      console.log('can', can);
      switch (organization.role) {
        case 'owner':
        case 'admin':
          can('manage', 'all');
          break;
        case 'manager':
        default:
          can(['read'], 'item');
          break;
      }
      this.ability = new Ability(rules);
    } catch (err) {
      console.log('Failed', err);
    }
  };

Log in console: 
'can': [Function: bound value]
'Failed', [TypeError: f is not a function. (In 'f(u.action)', 'f' is undefined)]

**Expected behavior**
Working on Release Mode.

**CASL Version**
  "@casl/ability": "^5.2.2",
  "@casl/react": "^2.2.2"

**Environment**:
$ node -v
v10.19.0

**Comment by stalniy** [comment] 2021-02-24 17:45
Is there anyway to reproduce issue in non react native env?

**Comment by stalniy** [comment] 2021-02-24 19:38
By the way, I don't have XCode and macbook to test this. You can try to make https://expo.io/ example. 

Without proper case to reproduce, I'll not be able to help with your issue

**Comment by GrowingCompany** [comment] 2021-02-25 01:38
> Is there anyway to reproduce issue in non react native env?

Thank you for reply.
I think I's only occurred in react native release env without expo.
Is 'CASL' support react native?
I try to find same case without XCode

**Comment by stalniy** [comment] 2021-02-25 06:43
I successfully ran casl with react native on my device with expo. But I do not have much experience in this so can’t say whether it was a dev or prod mode

**Comment by stalniy** [comment] 2021-02-25 06:44
Could you please include the whole stack trace?

**Comment by GrowingCompany** [comment] 2021-02-25 07:36
[](url)

**Comment by GrowingCompany** [comment] 2021-02-25 07:46
> I successfully ran casl with react native on my device with expo. But I do not have much experience in this so can’t say whether it was a dev or prod mode

My react native app is not with expo.
('React Native CLI Quickstart' https://reactnative.dev/docs/next/environment-setup)
It's to change debug to release env ref (https://stackoverflow.com/questions/28059697/how-do-i-toggle-between-debug-and-release-builds-in-xcode-6-7-8)

Already make a bundle on release env, so cannot see detail stack trace.
I also checked my crashlystics service, but no library level stack trace.
i will find solution to see stack trace

**Comment by stalniy** [comment] 2021-03-05 10:40
@GrowingCompany anything new on this topic?

**Comment by stalniy** [comment] 2021-03-30 10:34
I close this issue as there is no new details. @GrowingCompany please feel free to provide more accurate details and I'll try to help you

**Closed by stalniy** 2021-03-30 10:34 UTC
Labels: bug, status: needs more info

**Comment by davidfant** [comment] 2021-04-30 11:34
@GrowingCompany did you manage to resolve this? I'm hitting this issue on prod React Native builds with the following versions:
```
"@casl/ability": "^5.2.2",
"@casl/react": "^2.2.2",
"react-native": "^0.62.2",
```

`TypeError: f is not a function. (In 'f(u.action)', 'f' is undefined)`

**Comment by stalniy** [comment] 2021-04-30 12:05
@davidfant could you please setup test repo for me to take a look?

**Comment by davidfant** [comment] 2021-04-30 12:54
@stalniy I think I figured out the problem:
1. I was passing in `new Ability(undefined)` instead of an array. My data came from the backend which is why it was undefined until the array of abilities was fetched. TS didn't complain about me passing in a potentially undefined value (probably due to our somewhat lax tsconfig). That caused this function to have a non-array rules array: https://github.com/stalniy/casl/blob/6a4361a5ad17c50a199165e1541419b9e1174191/packages/casl-ability/src/RuleIndex.ts#L111
2. When compiled, the `wrapArray` function was undefined in the `dist/es6c/index.js` file. I created a function that looks exactly like wrapArray like this and it works:
```
    A(t) {
        const wrapArray = (t) => Array.isArray(t) ? t : [t];

        const s = new Map;
        for (let i = t.length - 1; i >= 0; i--) {
            const r = t.length - i - 1;
            const n = new y(t[i], this.p, r);
            const o = wrapArray(n.action); // changed e => wrapArray declared above
            const c = wrapArray(n.subject || "all"); // same
            m(this, n);
            for (let t = 0; t < c.length; t++) {
                const e = d(s, c[t], x);
                for (let t = 0; t < o.length; t++) d(e, o[t], $).rules.push(n)
            }
        }
        return s
    }
```
This is from these two lines in the code: https://github.com/stalniy/casl/blob/6a4361a5ad17c50a199165e1541419b9e1174191/packages/casl-ability/src/RuleIndex.ts#L145-L146

**Comment by stalniy** [comment] 2021-04-30 13:55
Hmmm... potentially there may be an issue if react-native compiles code into ES5. So, then some block scoped variables start to conflict

**Comment by stalniy** [comment] 2021-04-30 13:59
The target env  of es6c dist is pure nodejs. Maybe you need to tell react native to somehow use either es5m or umd dist file

**Comment by davidfant** [comment] 2021-04-30 16:05
@stalniy when I use `"main": "dist/es5m/index.js",` it works

**Comment by davidfant** [comment] 2021-04-30 16:10
I also don't need to default `undefined` to an empty array when using the `es5m` build
