### ISSUE TITLE
use multiple actions for single subject with abilityContext

### ISSUE THREAD

**Issue by skmohammadi** [stalniy/casl#731] opened 2023-01-26 07:35 UTC
**Describe the bug**
While the **can** method given by **AbilityBuilder** supports **multiple actions** for a **single subject**, the **can** method of **AbilityContext** gives a typescript error.

```ts
  const { can, rules, build } = new AbilityBuilder<AppAbility>(
    createMongoAbility
  );

  can(["delete", "edit"], "Content"); // this works without any TS error
  
  const ability = useAppAbility();
  ability.can(["create", "edit"], "Content") // this not works and gives TS error
```

**To Reproduce**
1. Ability configuration (rules, detectSubjectType, etc)
```ts
type AppAbility = MongoAbility<AppAbilities>;
const AbilityContext = createContext<AppAbility>(createMongoAbility());
const useAppAbility = () => useCaslAbility(AbilityContext);
```

2. How do you check abilities
```ts
  const ability = useAppAbility();
  ability.can(["create", "edit"], "Content") // this not works and gives a TS error
```

**Expected behavior**
It expects that the can method of AbilityContext supports multiple actions for a single subject, like the can method given by AbilityBuilder.

**CASL Version**

`@casl/ability` - v 6.3.3
`@casl/react` - v 3.1.0

**Environment**:

`typescript` - v 4.7.4

**Comment by stalniy** [comment] 2023-01-26 07:50
what logic do you expect from `  ability.can(["create", "edit"], "Content")`?

```ts
const result1 = ability.can("create", "Content") || ability.can("edit", "Content");
const result2 = ability.can("create", "Content") && ability.can("edit", "Content");

```

**Comment by skmohammadi** [comment] 2023-01-26 12:10
What is the logic in the following example:
```ts
const { can, rules, build } = new AbilityBuilder<AppAbility>(
    createMongoAbility
  );

  can(["delete", "edit"], "Content");
```

What do you think?

**Comment by stalniy** [comment] 2023-01-26 12:13
that is completely different context. in definition we just add rules. so, in that case it means add 2 rules for the same subject type.

**Comment by stalniy** [comment] 2023-01-26 12:18
close as duplicate of #679

**Closed by stalniy** 2023-01-26 12:18 UTC
Labels: enhancement
